(()=>{
 const tracks={home:['🇫🇷','Vorfreude auf Paris','audio/ambient-home.ogg'],road:['🚗','Leise Vorfreude unterwegs','audio/ambient-road.ogg'],hotel:['🏨','Ruhiger Morgen am Hotel','audio/ambient-hotel.ogg'],paris:['🪗','Französische Straßenmusik','audio/ambient-paris.ogg'],seine:['🌊','An der Seine','audio/ambient-seine.ogg'],cafe:['☕','Pariser Café','audio/ambient-cafe.ogg'],disney:['🏰','Magische Parkatmosphäre','audio/ambient-disney.ogg'],night:['✨','Paris bei Nacht','audio/ambient-night.ogg']};
 let enabled=localStorage.getItem('paris-ambient-enabled')==='1', current='', audio=new Audio();audio.loop=true;audio.preload='auto';audio.volume=Number(localStorage.getItem('paris-ambient-volume')||.28);
 const $=s=>document.querySelector(s); let position=null;
 function distance(a,b,c,d){const R=6371,p=Math.PI/180,x=(c-a)*p,y=(d-b)*p,q=Math.sin(x/2)**2+Math.cos(a*p)*Math.cos(c*p)*Math.sin(y/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
 function phase(){const now=new Date(),h=now.getHours(),date=now.toISOString().slice(0,10);let place='home';if(date>='2026-07-31'&&date<='2026-08-02')place='paris';if(date==='2026-07-31'&&h<11)place='road';if(position){const {latitude:la,longitude:lo}=position;if(distance(la,lo,48.8674,2.7836)<7)place='disney';else if(distance(la,lo,48.8584,2.2945)<3.5)place='seine';else if(distance(la,lo,48.7619,2.3046)<4)place='hotel';else if(distance(la,lo,48.8566,2.3522)<22)place=h>=21||h<6?'night':'paris';}else if(place==='paris'&&(h>=21||h<6))place='night';return place}
 function setTrack(place){if(current===place)return;current=place;const t=tracks[place]||tracks.paris;audio.pause();audio.src=t[2];$('#ambientIcon').textContent=t[0];$('#ambientTitle').textContent=t[1];$('#ambientSubtitle').textContent=position?'Automatisch nach eurem Standort':'Automatisch nach Reisephase und Tageszeit';document.body.dataset.ambientPlace=place;document.body.dataset.ambientTime=(new Date().getHours()>=20||new Date().getHours()<7)?'night':'day';if(enabled)audio.play().catch(()=>{});}
 function sync(){setTrack(phase());document.body.classList.toggle('ambient-on',enabled);const btn=$('#ambientToggle');btn.setAttribute('aria-pressed',String(enabled));$('#ambientToggleLabel').textContent=enabled?'Atmosphäre an':'Atmosphäre aus';if(enabled)audio.play().catch(()=>{});else audio.pause();localStorage.setItem('paris-ambient-enabled',enabled?'1':'0')}
 function gps(){if(!navigator.geolocation)return;const b=$('#ambientGPS');b.textContent='Standort wird ermittelt …';navigator.geolocation.watchPosition(p=>{position=p.coords;localStorage.setItem('paris-shared-location-v1',JSON.stringify({latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy,ts:Date.now()}));b.textContent='📍 Standort aktiv';b.classList.add('is-live');sync()},()=>{b.textContent='Standort nicht verfügbar'},{enableHighAccuracy:true,maximumAge:60000,timeout:12000})}
 function mount(){document.body.insertAdjacentHTML('beforeend',`<div class="ambient-scene" aria-hidden="true"></div><div class="ambient-panel" id="ambientPanel"><h3>✨ Atmosphäre</h3><p>Leise französische Musik und sanfte Soundscapes passen sich Reisephase, Tageszeit und auf Wunsch eurem Standort an – ohne unangenehmen Straßenlärm.</p><div class="ambient-now"><div class="ambient-icon" id="ambientIcon">🗼</div><div class="ambient-meta"><strong id="ambientTitle">Paris</strong><small id="ambientSubtitle">Automatisch angepasst</small></div></div><label class="ambient-volume"><span>Leise</span><input id="ambientVolume" type="range" min="0" max="0.65" step="0.01" value="${audio.volume}"><span>Lauter</span></label><small class="ambient-license">🎵 Enthält eine eigens komponierte, lizenzfreie französische Instrumentalbegleitung.</small><button class="ambient-location" id="ambientGPS" type="button">📍 Standort für passende Atmosphäre nutzen</button></div><button class="ambient-toggle" id="ambientToggle" type="button" aria-pressed="false"><span class="ambient-dot"></span><span id="ambientToggleLabel">Atmosphäre aus</span></button>`);
 const panel=$('#ambientPanel'),toggle=$('#ambientToggle');toggle.addEventListener('click',()=>{enabled=!enabled;panel.classList.add('is-open');sync()});$('#ambientVolume').addEventListener('input',e=>{audio.volume=Number(e.target.value);localStorage.setItem('paris-ambient-volume',String(audio.volume))});$('#ambientGPS').addEventListener('click',gps);document.addEventListener('click',e=>{if(!panel.contains(e.target)&&!toggle.contains(e.target))panel.classList.remove('is-open')});
 try{const saved=JSON.parse(localStorage.getItem('paris-shared-location-v1')||'null');if(saved&&Date.now()-saved.ts<86400000)position=saved}catch{}sync();setInterval(sync,60000);
 }
 document.readyState==='loading'?document.addEventListener('DOMContentLoaded',mount):mount();
})();
