(()=>{
 const tracks={
  home:['🇫🇷','Vorfreude auf Paris','ambient-home'],road:['🚗','Unterwegs nach Paris','ambient-road'],hotel:['🏨','Ruhiger Morgen am Hotel','ambient-hotel'],paris:['🪗','Leichte Pariser Straßenmusik','ambient-paris'],seine:['🌊','An der Seine','ambient-seine'],cafe:['☕','Pariser Café','ambient-cafe'],disney:['🏰','Magische Parkatmosphäre','ambient-disney'],night:['✨','Paris bei Nacht','ambient-night']
 };
 let enabled=localStorage.getItem('paris-ambient-enabled')==='1',current='',position=null;
 const audio=new Audio();audio.loop=true;audio.preload='auto';audio.playsInline=true;
 const stored=Number(localStorage.getItem('paris-ambient-volume'));audio.volume=Number.isFinite(stored)&&stored>=.05?Math.min(stored,.55):.28;
 const $=s=>document.querySelector(s);
 const ext=()=>audio.canPlayType('audio/mpeg')?'mp3':'ogg';
 function distance(a,b,c,d){const R=6371,p=Math.PI/180,x=(c-a)*p,y=(d-b)*p,q=Math.sin(x/2)**2+Math.cos(a*p)*Math.cos(c*p)*Math.sin(y/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
 function phase(){const now=new Date(),h=now.getHours(),date=now.toISOString().slice(0,10);let place='home';if(date>='2026-07-31'&&date<='2026-08-02')place='paris';if(date==='2026-07-31'&&h<11)place='road';if(position){const {latitude:la,longitude:lo}=position;if(distance(la,lo,48.8674,2.7836)<7)place='disney';else if(distance(la,lo,48.8584,2.2945)<3.5)place='seine';else if(distance(la,lo,48.7619,2.3046)<4)place='hotel';else if(distance(la,lo,48.8566,2.3522)<22)place=h>=21||h<6?'night':'paris'}else if(place==='paris'&&(h>=21||h<6))place='night';return place}
 function updateLabels(place){const t=tracks[place]||tracks.paris;$('#ambientIcon')&&($('#ambientIcon').textContent=t[0]);$('#ambientTitle')&&($('#ambientTitle').textContent=t[1]);$('#ambientSubtitle')&&($('#ambientSubtitle').textContent=position?'Automatisch nach eurem Standort':'Automatisch nach Reisephase und Tageszeit');document.body.dataset.ambientPlace=place;document.body.dataset.ambientTime=(new Date().getHours()>=20||new Date().getHours()<7)?'night':'day'}
 async function setTrack(place,playAfter=false){const t=tracks[place]||tracks.paris;if(current!==place){current=place;audio.pause();audio.src=`audio/${t[2]}.${ext()}`;audio.load();updateLabels(place)}if(enabled&&playAfter){try{audio.muted=false;if(audio.volume<.05)audio.volume=.28;await audio.play()}catch(err){console.warn('Atmosphäre konnte nicht gestartet werden',err)}}}
 function updateButtons(){document.body.classList.toggle('ambient-on',enabled);document.querySelectorAll('[data-ambient-toggle]').forEach(btn=>{btn.setAttribute('aria-pressed',String(enabled));btn.classList.toggle('is-on',enabled)});const label=$('#ambientToggleLabel');if(label)label.textContent=enabled?'Atmosphäre an':'Atmosphäre aus';const mainToggle=$('#ambientToggle');if(mainToggle){mainToggle.setAttribute('aria-label',enabled?'Atmosphäre ist an – Einstellungen öffnen':'Atmosphäre ist aus – Einstellungen öffnen');mainToggle.title=enabled?'Atmosphäre an':'Atmosphäre aus'};const rb=$('#revueSound');if(rb)rb.textContent=enabled?'🔊':'🔇'}
 async function sync(playAfter=false){await setTrack(phase(),playAfter);updateButtons();if(!enabled)audio.pause();localStorage.setItem('paris-ambient-enabled',enabled?'1':'0')}
 async function toggle(){enabled=!enabled;await sync(enabled)}
 function gps(){if(!navigator.geolocation)return;const b=$('#ambientGPS');if(b)b.textContent='Standort wird ermittelt …';navigator.geolocation.watchPosition(p=>{position=p.coords;localStorage.setItem('paris-shared-location-v1',JSON.stringify({latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy,ts:Date.now()}));if(b){b.textContent='📍 Standort aktiv';b.classList.add('is-live')}sync(enabled)},()=>{if(b)b.textContent='Standort nicht verfügbar'},{enableHighAccuracy:true,maximumAge:60000,timeout:12000})}
 function mountMain(){if($('#ambientToggle'))return;document.body.insertAdjacentHTML('beforeend',`<div class="ambient-scene" aria-hidden="true"></div><div class="ambient-panel" id="ambientPanel"><h3>✨ Atmosphäre</h3><p>Eine sanfte französische Instrumentalbegleitung passt sich Reisephase, Tageszeit und auf Wunsch eurem Standort an.</p><div class="ambient-now"><div class="ambient-icon" id="ambientIcon">🇫🇷</div><div class="ambient-meta"><strong id="ambientTitle">Vorfreude auf Paris</strong><small id="ambientSubtitle">Automatisch angepasst</small></div></div><label class="ambient-volume"><span>Leise</span><input id="ambientVolume" type="range" min="0.05" max="0.55" step="0.01" value="${audio.volume}"><span>Lauter</span></label><small class="ambient-license">🎵 Ruhige Instrumentalmusik ohne Verkehrs- oder Straßengeräusche.</small><button class="ambient-location" id="ambientGPS" type="button">📍 Standort für passende Atmosphäre nutzen</button></div><button class="ambient-toggle" id="ambientToggle" data-ambient-toggle type="button" aria-pressed="false" aria-label="Atmosphäre öffnen" title="Atmosphäre"><span class="ambient-toggle-glyph" aria-hidden="true">♫</span><span class="ambient-dot" aria-hidden="true"></span><span class="ambient-toggle-text" id="ambientToggleLabel">Atmosphäre aus</span></button>`);const panel=$('#ambientPanel'),button=$('#ambientToggle');button.addEventListener('click',async e=>{e.stopPropagation();await toggle();panel.classList.add('is-open')});$('#ambientVolume').addEventListener('input',e=>{audio.volume=Number(e.target.value);localStorage.setItem('paris-ambient-volume',String(audio.volume));if(enabled&&audio.paused)audio.play().catch(()=>{})});$('#ambientGPS').addEventListener('click',gps);document.addEventListener('click',e=>{if(!panel.contains(e.target)&&!button.contains(e.target))panel.classList.remove('is-open')})}
 function mountRevue(){document.body.classList.add('ambient-revue-mode');const btn=$('#revueSound');if(btn){btn.dataset.ambientToggle='';btn.addEventListener('click',toggle)}}
 try{const saved=JSON.parse(localStorage.getItem('paris-shared-location-v1')||'null');if(saved&&Date.now()-saved.ts<86400000)position=saved}catch{}
 function mount(){document.querySelector('.revue-app')?mountRevue():mountMain();sync(false);setInterval(()=>sync(false),60000)}
 window.ParisAmbient={toggle,play:()=>{enabled=true;return sync(true)},pause:()=>{enabled=false;return sync(false)},isEnabled:()=>enabled};
 document.readyState==='loading'?document.addEventListener('DOMContentLoaded',mount):mount();
})();
