(() => {
  'use strict';
  const DAYS=['2026-07-31','2026-08-01','2026-08-02'];
  const state={closures:new Map(),stats:[],photoRows:[],liveRows:[],photosByDay:new Map(),owner:localStorage.getItem('parisDeviceOwner')||'',activeDay:null,editing:new Set(),saving:new Set(),refreshing:false};
  const sections=[...document.querySelectorAll('[data-day-closure]')];
  if(!sections.length) return;
  const photoModal=document.getElementById('closurePhotoModal'),stepsModal=document.getElementById('closureStepsModal');
  const fmt=n=>Number.isFinite(Number(n))?Number(n).toLocaleString('de-DE'):'–';
  const dayKey=value=>{if(!value)return'';try{return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Paris',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(value))}catch{return String(value).slice(0,10)}};
  const memberName=()=>window.ParisCloud?.memberName||state.owner||'Gemeinsam';
  const fieldKey=(day,field)=>`${day}:${field}`;
  function byline(meta){if(!meta?.name)return'Noch nicht ausgefüllt';const time=meta.at?new Date(meta.at).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'}):'';return `${meta.name}${time?' · '+time:''}`}
  function stepValues(day){
    const rows=state.stats.filter(r=>r.trip_day===day), values={Fabian:null,Luisa:null};
    rows.forEach(r=>{if(r.member_name==='Fabian'||r.member_name==='Luisa')values[r.member_name]=r.steps});
    const nums=Object.values(values).filter(v=>Number.isFinite(Number(v))).map(Number);
    return {...values,average:nums.length?Math.round(nums.reduce((a,b)=>a+b,0)/nums.length):null};
  }
  function renderSection(section){
    const day=section.dataset.dayClosure,c=state.closures.get(day)||{field_meta:{}};
    section.querySelector('[data-photo-count]').textContent=fmt((state.photoRows||[]).filter(r=>dayKey(r.taken_at||r.created_at)===day).length);
    section.querySelector('[data-live-count]').textContent=fmt((state.liveRows||[]).filter(r=>dayKey(r.collected_at)===day).length);
    const sv=stepValues(day);section.querySelector('[data-steps-average]').textContent=fmt(sv.average);section.querySelector('[data-steps-detail]').textContent=`Fabian ${fmt(sv.Fabian)} · Luisa ${fmt(sv.Luisa)}`;
    ['best_moment','shared_note','lasting_memory'].forEach(field=>{
      const input=section.querySelector(`[data-field="${field}"]`); if(input&&!state.editing.has(fieldKey(day,field))&&document.activeElement!==input)input.value=c[field]||'';
      const line=section.querySelector(`[data-byline="${field}"]`);if(line)line.textContent=byline(c.field_meta?.[field]);
    });
    const stars=section.querySelector('[data-rating-stars]');if(stars){stars.innerHTML='';for(let i=1;i<=5;i++){const b=document.createElement('button');b.type='button';b.className='closure-star'+(i<=Number(c.day_rating||0)?' is-active':'');b.textContent='★';b.setAttribute('aria-label',`${i} von 5 Sternen`);b.onclick=()=>saveField(day,'day_rating',i);stars.appendChild(b)}}
    section.querySelector('[data-rating-caption]').textContent=c.day_rating?`${c.day_rating} von 5`:'Noch nicht bewertet';
    const food=section.querySelector('[data-food-rating]');if(food){const labels=['Schlecht','Na ja','Okay','Gut','Fantastisch'],faces=['☹','◔','☺','☻','♡'];food.innerHTML='';labels.forEach((label,i)=>{const b=document.createElement('button');b.type='button';b.className='food-choice'+(Number(c.food_rating)===i+1?' is-active':'');b.innerHTML=`<span>${faces[i]}</span>${label}`;b.onclick=()=>saveField(day,'food_rating',i+1);food.appendChild(b)})}
    ['day_rating','food_rating','favorite_photo_id'].forEach(field=>{const line=section.querySelector(`[data-byline="${field}"]`);if(line)line.textContent=field==='favorite_photo_id'&&!c[field]?'Noch nicht gewählt':byline(c.field_meta?.[field])});
    renderFavorite(section,day,c.favorite_photo_id);
    section.querySelector('[data-last-sync]').textContent=c.updated_at?`Zuletzt synchronisiert: ${new Date(c.updated_at).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})}`:'Noch kein Eintrag';
  }
  async function renderFavorite(section,day,id){const box=section.querySelector('[data-photo-preview]');if(!box)return;if(!id){box.innerHTML='<span>♡</span><p>Noch kein Lieblingsfoto gewählt</p>';return}const photo=(state.photosByDay.get(day)||[]).find(p=>String(p.id)===String(id));if(photo?.url){box.innerHTML=`<img src="${photo.url}" alt="Lieblingsfoto des Tages">`}else box.innerHTML='<span>♡</span><p>Foto wird geladen …</p>'}
  function render(){sections.forEach(renderSection);const profileName=window.ParisCloud?.memberName||state.owner;document.querySelectorAll('.closure-person-switch').forEach(box=>{if(window.ParisCloud?.memberName){box.innerHTML=`<small>Dieses Gerät:</small><strong>${window.ParisCloud.memberName}</strong>`}});document.querySelectorAll('[data-global-owner]').forEach(b=>b.classList.toggle('is-active',b.dataset.globalOwner===state.owner));if(!stepsModal.hidden)renderStepsModal()}
  async function refresh(){if(state.refreshing)return;state.refreshing=true;try{
    const [all,photoRows,liveRows]=await Promise.all([window.ParisSync.dayClosure.list(),window.ParisSync.dayClosure.photoRows(),window.ParisSync.dayClosure.liveRows()]);
    state.closures=new Map(all.closures.map(c=>[c.day,c]));state.stats=all.stats;state.photoRows=photoRows;state.liveRows=liveRows;render();
  }catch(e){console.warn('Tagesabschluss-Abgleich:',e.message)}finally{state.refreshing=false}}
  async function saveField(day,field,value){const key=fieldKey(day,field);state.saving.add(key);const old=state.closures.get(day)||{day,field_meta:{}};state.closures.set(day,{...old,[field]:value,field_meta:{...(old.field_meta||{}),[field]:{name:memberName(),at:new Date().toISOString()}}});render();try{const saved=await window.ParisSync.dayClosure.saveField(day,field,value,memberName());state.closures.set(day,saved)}catch(e){console.warn('Tagesabschluss speichern:',e);await refresh()}finally{state.saving.delete(key);render()}}
  function bindInputs(){sections.forEach(section=>{const day=section.dataset.dayClosure;section.querySelectorAll('[data-field]').forEach(input=>{const field=input.dataset.field,key=fieldKey(day,field);let timer;input.addEventListener('focus',()=>state.editing.add(key));input.addEventListener('input',()=>{state.editing.add(key);clearTimeout(timer);timer=setTimeout(()=>saveField(day,field,input.value),850)});input.addEventListener('blur',()=>{clearTimeout(timer);saveField(day,field,input.value).finally(()=>setTimeout(()=>state.editing.delete(key),350))})});section.querySelector('[data-select-photo]').onclick=()=>openPhotoPicker(day);section.querySelector('[data-open-steps]').onclick=()=>openSteps(day)})}
  async function ensurePhotos(day){if(state.photosByDay.has(day))return state.photosByDay.get(day);const all=await window.ParisSync.gallery.list();const arr=all.filter(p=>dayKey(p.takenAt||p.createdAt)===day).map(p=>({...p,url:URL.createObjectURL(p.blob)}));state.photosByDay.set(day,arr);return arr}
  async function openPhotoPicker(day){state.activeDay=day;photoModal.hidden=false;const grid=photoModal.querySelector('[data-photo-grid]');grid.innerHTML='<div class="closure-photo-empty">Fotos werden geladen …</div>';try{const photos=await ensurePhotos(day),selected=state.closures.get(day)?.favorite_photo_id;if(!photos.length){grid.innerHTML='<div class="closure-photo-empty">Für diesen Tag gibt es noch keine Fotos in der Reisegalerie.</div>';return}grid.innerHTML='';photos.forEach(p=>{const b=document.createElement('button');b.type='button';b.className='closure-photo-option'+(String(selected)===String(p.id)?' is-selected':'');b.innerHTML=`<img src="${p.url}" alt="${(p.caption||'Reisefoto').replace(/"/g,'&quot;')}"><span>${p.caption||'Foto auswählen'}</span>`;b.onclick=async()=>{await saveField(day,'favorite_photo_id',p.id);photoModal.hidden=true};grid.appendChild(b)})}catch(e){grid.innerHTML=`<div class="closure-photo-empty">Fotos konnten nicht geladen werden: ${e.message}</div>`}}
  function openSteps(day){state.activeDay=day;stepsModal.hidden=false;renderStepsModal()}
  function renderStepsModal(){const v=stepValues(state.activeDay);stepsModal.querySelector('[data-modal-fabian]').textContent=fmt(v.Fabian);stepsModal.querySelector('[data-modal-luisa]').textContent=fmt(v.Luisa);stepsModal.querySelector('[data-modal-average]').textContent=fmt(v.average);stepsModal.querySelectorAll('[data-owner]').forEach(b=>b.classList.toggle('is-active',b.dataset.owner===state.owner));stepsModal.querySelector('[data-current-owner]').textContent=state.owner?`${state.owner}s Schritte`:'Bitte Gerät auswählen';const own=state.owner?v[state.owner]:null;const input=stepsModal.querySelector('[data-own-steps]');if(document.activeElement!==input)input.value=own??''}
  function bindOwnerSwitches(){document.querySelectorAll('[data-global-owner]').forEach(b=>b.onclick=()=>{state.owner=b.dataset.globalOwner;localStorage.setItem('parisDeviceOwner',state.owner);render()})}
  function bindModals(){document.querySelectorAll('[data-close-photo]').forEach(b=>b.onclick=()=>photoModal.hidden=true);document.querySelectorAll('[data-close-steps]').forEach(b=>b.onclick=()=>stepsModal.hidden=true);[photoModal,stepsModal].forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.hidden=true}));stepsModal.querySelectorAll('[data-owner]').forEach(b=>b.onclick=()=>{state.owner=b.dataset.owner;localStorage.setItem('parisDeviceOwner',state.owner);renderStepsModal()});stepsModal.querySelector('[data-save-steps]').onclick=async()=>{if(!state.owner){alert('Bitte zuerst Fabian oder Luisa für dieses Gerät auswählen.');return}const input=stepsModal.querySelector('[data-own-steps]'),steps=Number(input.value);if(!Number.isFinite(steps)||steps<0){alert('Bitte eine gültige Schrittzahl eingeben.');return}await window.ParisSync.dayClosure.saveSteps(state.activeDay,steps,state.owner);await refresh()}}
  async function importHealthQuery(){const p=new URLSearchParams(location.search),steps=p.get('health_steps'),day=p.get('health_date'),owner=p.get('health_member');if(!steps||!DAYS.includes(day)||!['Fabian','Luisa'].includes(owner))return;state.owner=owner;localStorage.setItem('parisDeviceOwner',owner);try{await window.ParisSync.dayClosure.saveSteps(day,Number(steps),owner);p.delete('health_steps');p.delete('health_date');p.delete('health_member');history.replaceState({},'',location.pathname+(p.toString()?'?'+p:'' )+location.hash)}catch(e){console.warn('Health-Import:',e)}}
  bindInputs();bindOwnerSwitches();bindModals();
  (async()=>{try{await window.ParisSync.ready;if(window.ParisCloud?.memberName){state.owner=window.ParisCloud.memberName;localStorage.setItem('parisDeviceOwner',state.owner)}await importHealthQuery();await refresh();await window.ParisSync.dayClosure.subscribe(refresh);setInterval(()=>{if(!document.hidden)refresh()},2500);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh()});window.addEventListener('focus',refresh);document.addEventListener('paris:cloud-updated',e=>{if(e.detail?.key?.includes('gallery')){state.photosByDay.clear();refresh()}})}catch(e){console.warn('Tagesabschluss Cloudstart:',e.message)}})();
})();
