(()=>{'use strict';
const PLACES=[
{name:'Eiffelturm',lat:48.85837,lng:2.29448,radius:700,icon:'🗼',fact:'Der Turm wurde für die Weltausstellung 1889 errichtet.',phrase:'Où est le meilleur point de vue ? · Wo ist der beste Aussichtspunkt?',tip:'Für Familienfotos wirkt der Blick vom Trocadéro am frühen Morgen besonders ruhig.'},
{name:'Disneyland Paris',lat:48.87223,lng:2.77581,radius:1600,icon:'🏰',fact:'Der Park öffnete 1992 und ist heute eines der meistbesuchten Reiseziele Europas.',phrase:'Où est le Baby Care Center ? · Wo ist das Baby Care Center?',tip:'Nehmt ein Foto vor dem Schloss auf, bevor es später voller wird.'},
{name:'Louvre',lat:48.86061,lng:2.33764,radius:650,icon:'🎨',fact:'Der Louvre war ursprünglich eine mittelalterliche Festung.',phrase:'Où se trouve l’entrée ? · Wo befindet sich der Eingang?',tip:'Die seitlichen Höfe liefern oft ruhigere Bilder als direkt vor der Pyramide.'},
{name:'Seine',lat:48.8566,lng:2.3429,radius:850,icon:'⛵',fact:'Die Seine durchquert Paris auf rund 13 Kilometern.',phrase:'À quelle heure part le bateau ? · Wann fährt das Boot ab?',tip:'Am Wasser entstehen besonders schöne Bilder kurz vor Sonnenuntergang.'},
{name:'Montmartre',lat:48.8867,lng:2.3431,radius:900,icon:'🎨',fact:'Montmartre war lange das Zuhause vieler Künstlerinnen und Künstler.',phrase:'C’est loin à pied ? · Ist es zu Fuß weit?',tip:'Kleine Seitenstraßen wirken oft stimmungsvoller als der Platz direkt vor Sacré-Cœur.'},
{name:'Hôtel de Berny',lat:48.7616,lng:2.3059,radius:900,icon:'🏨',fact:'Euer ruhiger Ausgangspunkt südlich von Paris.',phrase:'Nous avons une réservation. · Wir haben eine Reservierung.',tip:'Ein erstes Ankunftsfoto macht später den Beginn der Reisegeschichte sichtbar.'}
];
const $=s=>document.querySelector(s), KEY='parisLiveVisitedV1'; let watchId=null;
const distance=(a,b,c,d)=>{const R=6371000,p=Math.PI/180,x=(c-a)*p,y=(d-b)*p;const q=Math.sin(x/2)**2+Math.cos(a*p)*Math.cos(c*p)*Math.sin(y/2)**2;return 2*R*Math.asin(Math.sqrt(q))};
const visited=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}};
function saveVisit(place){const list=visited();if(!list.some(x=>x.name===place.name))list.push({name:place.name,icon:place.icon,at:new Date().toISOString()});localStorage.setItem(KEY,JSON.stringify(list));renderHistory()}
function renderHistory(){const el=$('#liveHistory');if(!el)return;const list=visited();el.innerHTML=list.length?list.map(x=>`<span class="live-history-chip">${x.icon} ${x.name} besucht</span>`).join(''):'<span class="live-history-chip">Noch keine Orte als besucht gespeichert</span>'}
function show(place,meters){const result=$('#liveResult');result.innerHTML=`<article class="live-place-card"><div class="live-place-head"><div><span class="live-kicker">${place.icon} Live Moment</span><h3>Ihr seid gerade ${place.name==='Hôtel de Berny'?'im':'am'} ${place.name}</h3></div><span class="live-distance">${meters<1000?Math.round(meters)+' m':(meters/1000).toFixed(1)+' km'} entfernt</span></div><div class="live-detail-grid"><div class="live-detail"><span>✨</span><strong>Wusstet ihr?</strong><small>${place.fact}</small></div><div class="live-detail"><span>💬</span><strong>Passender Satz</strong><small>${place.phrase}</small></div><div class="live-detail"><span>📷</span><strong>Fototipp</strong><small>${place.tip}</small></div></div><div class="live-moment-actions"><button class="live-visited" type="button">❤️ Diesen Moment merken</button><button class="live-photo-jump" type="button">📷 Jetzt Polaroid auswählen</button></div></article>`;result.classList.add('show');$('.live-visited').onclick=()=>{saveVisit(place);$('.live-visited').textContent='✓ Moment gespeichert'};$('.live-photo-jump').onclick=()=>$('#reisegalerie')?.scrollIntoView({behavior:'smooth'});}
function locate(){const status=$('#liveStatus');if(!navigator.geolocation){status.lastElementChild.textContent='GPS wird von diesem Browser nicht unterstützt.';return}status.classList.add('is-live');status.lastElementChild.textContent='Standort wird bestimmt …';navigator.geolocation.getCurrentPosition(pos=>{const p=PLACES.map(x=>({...x,d:distance(pos.coords.latitude,pos.coords.longitude,x.lat,x.lng)})).sort((a,b)=>a.d-b.d)[0];status.lastElementChild.textContent=p.d<=p.radius?`Live erkannt: ${p.name}`:`Nächster Reisemoment: ${p.name}`;show(p,p.d)},()=>{status.classList.remove('is-live');status.lastElementChild.textContent='Standort konnte nicht freigegeben werden.'},{enableHighAccuracy:true,timeout:12000,maximumAge:60000})}
function init(){const btn=$('#activateLiveMoments');if(!btn)return;btn.onclick=locate;$('#showPlannedMoment').onclick=()=>show(PLACES[0],0);renderHistory()}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init,{once:true}):init();
})();
