(function(){
  'use strict';
  const root=document.getElementById('sprachcoach'); if(!root) return;
  const categories=[
    {id:'hotel',icon:'🏨',label:'Hotel'},{id:'restaurant',icon:'🍝',label:'Restaurant'},{id:'cafe',icon:'🥐',label:'Café & Bäckerei'},{id:'transport',icon:'🚇',label:'Metro & Bus'},{id:'disney',icon:'🏰',label:'Disneyland'},{id:'shopping',icon:'🛍️',label:'Shopping'},{id:'baby',icon:'👶',label:'Mit Baby'},{id:'emergency',icon:'🚨',label:'Notfall'}
  ];
  const phrases=[
    ['hotel','Reservierung','Wir haben eine Reservierung.','Bonjour, nous avons une réservation.','Hello, we have a reservation.','Bon-schur, nu sawong ün reserwassjong.'],
    ['hotel','Check-in','Können wir schon früher einchecken?','Est-ce que nous pouvons arriver plus tôt ?','Can we check in earlier?','Ess kö nu puwong arriwe plü to?'],
    ['hotel','Zimmer','Ist unser Zimmer schon fertig?','Est-ce que notre chambre est prête ?','Is our room ready yet?','Ess kö notr schombr eh prett?'],
    ['hotel','Gepäck','Können wir unser Gepäck hier lassen?','Pouvons-nous laisser nos bagages ici ?','Can we leave our luggage here?','Puwong nu lesseh no bagasch issi?'],
    ['hotel','WLAN','Wie lautet das WLAN-Passwort?','Quel est le mot de passe Wi-Fi ?','What is the Wi-Fi password?','Kell eh lö mo dö pass Wi-Fi?'],
    ['hotel','Aufzug','Wo ist der Aufzug?','Où est l’ascenseur ?','Where is the elevator?','U eh lassong-sör?'],
    ['restaurant','Reservierung','Guten Abend, wir haben eine Reservierung.','Bonsoir, nous avons une réservation.','Good evening, we have a reservation.','Bon-swar, nu sawong ün reserwassjong.'],
    ['restaurant','Vegetarisch','Ist dieses Gericht vegetarisch?','Est-ce que ce plat est végétarien ?','Is this dish vegetarian?','Ess kö sö pla eh weschetariäng?'],
    ['restaurant','Ohne Fleisch','Bitte ohne Fleisch und ohne Fisch.','Sans viande et sans poisson, s’il vous plaît.','No meat and no fish, please.','Song wiand eh song pwassong, sill wu plä.'],
    ['restaurant','Bestellen','Wir möchten gern bestellen.','Nous voudrions commander, s’il vous plaît.','We would like to order, please.','Nu wudriong komondeh, sill wu plä.'],
    ['restaurant','Empfehlung','Was können Sie empfehlen?','Qu’est-ce que vous recommandez ?','What do you recommend?','Kess kö wu rökomondeh?'],
    ['restaurant','Rechnung','Die Rechnung bitte.','L’addition, s’il vous plaît.','The bill, please.','Laddissjong, sill wu plä.'],
    ['restaurant','Lob','Es war sehr lecker, vielen Dank.','C’était délicieux, merci beaucoup.','It was delicious, thank you very much.','Seteh delissjö, märssi boku.'],
    ['cafe','Bestellung','Einen Cappuccino bitte.','Un cappuccino, s’il vous plaît.','A cappuccino, please.','Öng kappütschino, sill wu plä.'],
    ['cafe','Mitnehmen','Zum Mitnehmen, bitte.','À emporter, s’il vous plaît.','To take away, please.','A ongporteh, sill wu plä.'],
    ['cafe','Hafermilch','Haben Sie Hafermilch?','Avez-vous du lait d’avoine ?','Do you have oat milk?','Aweh wu dü leh dawuan?'],
    ['cafe','Bäckerei','Zwei Croissants und ein Baguette, bitte.','Deux croissants et une baguette, s’il vous plaît.','Two croissants and one baguette, please.','Dö croassong eh ün bagett, sill wu plä.'],
    ['cafe','Zahlen','Kann ich mit Karte bezahlen?','Je peux payer par carte ?','Can I pay by card?','Schö pö peje par kart?'],
    ['transport','Richtung','Welche Linie fährt zum Louvre?','Quelle ligne va au Louvre ?','Which line goes to the Louvre?','Kell linj wa o Luwr?'],
    ['transport','Umsteigen','Wo müssen wir umsteigen?','Où devons-nous changer ?','Where do we need to change?','U döwong nu schongscheh?'],
    ['transport','Bahnsteig','Wo ist der richtige Bahnsteig?','Où est le bon quai ?','Where is the correct platform?','U eh lö bong keh?'],
    ['transport','Kinderwagen','Ist dieser Eingang mit Kinderwagen zugänglich?','Cette entrée est-elle accessible avec une poussette ?','Is this entrance accessible with a stroller?','Sett ongtreh eh tell akssessibl aweck ün pussett?'],
    ['transport','Ticket','Welches Ticket brauchen wir?','Quel billet devons-nous prendre ?','Which ticket do we need?','Kell bijeh döwong nu prondr?'],
    ['transport','Haltestelle','Ist das die richtige Haltestelle?','C’est le bon arrêt ?','Is this the right stop?','Seh lö bong arreh?'],
    ['disney','Parade','Wo beginnt die Parade?','Où commence la parade ?','Where does the parade start?','U komongss la parad?'],
    ['disney','Baby Care','Wo ist das Baby Care Center?','Où se trouve le Baby Care Center ?','Where is the Baby Care Center?','U sö truw lö Baby Care Center?'],
    ['disney','Attraktion','Wie lange ist die Wartezeit?','Combien de temps faut-il attendre ?','How long is the wait?','Kombiäng dö tong fo till atondr?'],
    ['disney','Kinderwagen','Wo können wir den Kinderwagen abstellen?','Où pouvons-nous laisser la poussette ?','Where can we leave the stroller?','U puwong nu lesseh la pussett?'],
    ['disney','Rider Switch','Gibt es hier Rider Switch?','Est-ce qu’il y a le Rider Switch ici ?','Is Rider Switch available here?','Ess kill ja lö Rider Switch issi?'],
    ['disney','Show','Wann beginnt die nächste Show?','À quelle heure commence le prochain spectacle ?','When does the next show start?','A kell ör komongss lö proschäng spektakl?'],
    ['shopping','Preis','Wie viel kostet das?','Combien ça coûte ?','How much does this cost?','Kombiäng sa kut?'],
    ['shopping','Größe','Haben Sie das in einer anderen Größe?','Vous l’avez dans une autre taille ?','Do you have this in another size?','Wu lawe dong sün otr taj?'],
    ['shopping','Anprobieren','Kann ich das anprobieren?','Je peux l’essayer ?','Can I try this on?','Schö pö lessäjeh?'],
    ['shopping','Kasse','Wo ist die Kasse?','Où est la caisse ?','Where is the checkout?','U eh la kess?'],
    ['shopping','Steuer','Kann ich eine Quittung bekommen?','Puis-je avoir un reçu ?','Can I get a receipt?','Püisch awuar öng ressü?'],
    ['baby','Flasche','Können Sie die Flasche bitte aufwärmen?','Pouvez-vous réchauffer le biberon, s’il vous plaît ?','Could you warm the bottle, please?','Puweh wu reschofeh lö bibrong, sill wu plä?'],
    ['baby','Wickelraum','Gibt es einen Wickelraum?','Y a-t-il une table à langer ?','Is there a changing room?','Ja till ün tabl a longscheh?'],
    ['baby','Hochstuhl','Haben Sie einen Hochstuhl?','Avez-vous une chaise haute ?','Do you have a high chair?','Aweh wu ün schäss ot?'],
    ['baby','Aufzug','Wo ist der Aufzug für den Kinderwagen?','Où est l’ascenseur pour la poussette ?','Where is the elevator for the stroller?','U eh lassong-sör pur la pussett?'],
    ['baby','Ruhe','Gibt es hier einen ruhigen Ort für das Baby?','Y a-t-il un endroit calme pour le bébé ?','Is there a quiet place for the baby?','Ja till öng ondrua kalm pur lö bebe?'],
    ['baby','Zugang','Darf der Kinderwagen mit hinein?','Est-ce que la poussette peut entrer ?','Can the stroller go inside?','Ess kö la pussett pö ongtreh?'],
    ['emergency','Hilfe','Ich brauche Hilfe.','J’ai besoin d’aide.','I need help.','Scheh bösuäng ded.'],
    ['emergency','Arzt','Rufen Sie bitte einen Arzt.','Appelez un médecin, s’il vous plaît.','Please call a doctor.','Appleh öng medssäng, sill wu plä.'],
    ['emergency','Verloren','Ich habe mein Portemonnaie verloren.','J’ai perdu mon portefeuille.','I lost my wallet.','Scheh perdü mong portföj.'],
    ['emergency','Polizei','Wo ist die nächste Polizeistation?','Où est le commissariat le plus proche ?','Where is the nearest police station?','U eh lö komissaria lö plü prosch?'],
    ['emergency','Kind','Wir suchen unser Kind.','Nous cherchons notre enfant.','We are looking for our child.','Nu scherschong notr ongfong.'],
    ['emergency','Apotheke','Wo ist die nächste Apotheke?','Où est la pharmacie la plus proche ?','Where is the nearest pharmacy?','U eh la farmassi la plü prosch?']
  ].map((p,i)=>({id:'p'+i,category:p[0],topic:p[1],de:p[2],fr:p[3],en:p[4],pron:p[5]}));
  const situations=[
    {id:'hotel-checkin',category:'hotel',icon:'🏨',title:'An der Rezeption',reason:'Passend zu eurer Ankunft im Hôtel de Berny',coords:[48.7619,2.3049],radius:650,lines:[['👩','Réception','Bonjour, vous avez une réservation ?','Hello, do you have a reservation?','Guten Tag, haben Sie eine Reservierung?'],['🙂','Ihr','Oui, au nom de Klaas.','Yes, under the name Klaas.','Ja, auf den Namen Klaas.'],['👩','Réception','Puis-je voir votre pièce d’identité ?','May I see your ID?','Darf ich Ihren Ausweis sehen?']]},
    {id:'perruche',category:'restaurant',icon:'🍝',title:'Heute Abend bei Perruche',reason:'Reservierung, Platzwunsch und vegetarische Bestellung',coords:[48.8737,2.3255],radius:700,lines:[['👩','Service','Bonsoir, vous avez réservé ?','Good evening, do you have a reservation?','Guten Abend, haben Sie reserviert?'],['🙂','Ihr','Oui, au nom de Klaas. Une table près de la fenêtre, si possible.','Yes, under the name Klaas. A table near the window, if possible.','Ja, auf den Namen Klaas. Einen Tisch am Fenster, wenn möglich.'],['🙂','Ihr','Quels plats sont végétariens ?','Which dishes are vegetarian?','Welche Gerichte sind vegetarisch?']]},
    {id:'elio',category:'restaurant',icon:'🌇',title:'Abschlussdinner im Elio',reason:'Der passende Dialog vor eurer Reservierung',coords:[48.8509,2.2924],radius:700,lines:[['🙂','Ihr','Bonjour, nous avons une réservation à dix-sept heures trente.','Hello, we have a reservation at 5:30 p.m.','Guten Tag, wir haben um 17:30 Uhr reserviert.'],['👩','Service','Au nom de qui ?','Under what name?','Auf welchen Namen?'],['🙂','Ihr','Au nom de Klaas, avec une poussette.','Under the name Klaas, with a stroller.','Auf den Namen Klaas, mit Kinderwagen.']]},
    {id:'disney',category:'disney',icon:'🏰',title:'Im Disneyland Paris',reason:'Parade, Baby Care Center und Kinderwagen',coords:[48.8722,2.7758],radius:2200,lines:[['🙂','Ihr','Où commence la parade ?','Where does the parade start?','Wo beginnt die Parade?'],['👩','Cast Member','Elle commence près de Main Street.','It starts near Main Street.','Sie beginnt in der Nähe der Main Street.'],['🙂','Ihr','Et où est le Baby Care Center ?','And where is the Baby Care Center?','Und wo ist das Baby Care Center?']]},
    {id:'louvre',category:'transport',icon:'🎫',title:'Am Louvre',reason:'Tickets und der richtige Eingang',coords:[48.8606,2.3376],radius:750,lines:[['🙂','Ihr','Excusez-moi, où est l’entrée avec réservation ?','Excuse me, where is the entrance for reservations?','Entschuldigung, wo ist der Eingang mit Reservierung?'],['👨','Mitarbeiter','Continuez tout droit, puis à gauche.','Go straight ahead, then turn left.','Gehen Sie geradeaus und dann links.'],['🙂','Ihr','Merci beaucoup.','Thank you very much.','Vielen Dank.']]},
    {id:'eiffel',category:'transport',icon:'🗼',title:'Rund um den Eiffelturm',reason:'Nach dem Weg oder der nächsten Metro fragen',coords:[48.8584,2.2945],radius:900,lines:[['🙂','Ihr','Où est la station de métro la plus proche ?','Where is the nearest metro station?','Wo ist die nächste Metrostation?'],['👨','Passant','C’est à environ cinq minutes à pied.','It is about a five-minute walk.','Sie ist ungefähr fünf Minuten zu Fuß entfernt.'],['🙂','Ihr','Merci !','Thank you!','Danke!']]},
    {id:'cafe',category:'cafe',icon:'🥐',title:'Im Café oder in der Bäckerei',reason:'Bestellen, mitnehmen und bezahlen',lines:[['🙂','Ihr','Bonjour, deux croissants et un cappuccino, s’il vous plaît.','Hello, two croissants and a cappuccino, please.','Guten Tag, zwei Croissants und einen Cappuccino bitte.'],['👩','Verkauf','Sur place ou à emporter ?','For here or to go?','Hier essen oder zum Mitnehmen?'],['🙂','Ihr','À emporter, merci. Je peux payer par carte ?','To go, thank you. Can I pay by card?','Zum Mitnehmen, danke. Kann ich mit Karte zahlen?']]},
    {id:'metro',category:'transport',icon:'🚇',title:'Unterwegs mit Metro und RER',reason:'Linie, Umstieg und Bahnsteig schnell klären',lines:[['🙂','Ihr','Quelle ligne va au centre de Paris ?','Which line goes to central Paris?','Welche Linie fährt ins Zentrum von Paris?'],['👨','Passant','Prenez le RER B et changez à Châtelet.','Take the RER B and change at Châtelet.','Nehmen Sie die RER B und steigen Sie in Châtelet um.'],['🙂','Ihr','De quel quai part le train ?','Which platform does the train leave from?','Von welchem Bahnsteig fährt der Zug?']]},
    {id:'baby',category:'baby',icon:'👶',title:'Mit Livi unterwegs',reason:'Wickeln, Flasche und ein ruhiger Platz',lines:[['🙂','Ihr','Y a-t-il une table à langer ?','Is there a baby changing table?','Gibt es einen Wickeltisch?'],['🙂','Ihr','Pouvez-vous réchauffer le biberon ?','Could you warm the baby bottle?','Können Sie die Flasche aufwärmen?'],['🙂','Ihr','Y a-t-il un endroit calme pour le bébé ?','Is there a quiet place for the baby?','Gibt es einen ruhigen Ort für das Baby?']]},
    {id:'shopping',category:'shopping',icon:'🛍️',title:'Beim Shopping',reason:'Größe, Preis und Kartenzahlung',lines:[['🙂','Ihr','Avez-vous cette taille ?','Do you have this size?','Haben Sie diese Größe?'],['👩','Verkauf','Je vais vérifier.','I will check.','Ich schaue nach.'],['🙂','Ihr','Puis-je payer par carte ?','Can I pay by card?','Kann ich mit Karte zahlen?']]},
    {id:'emergency',category:'emergency',icon:'🚨',title:'Im Notfall',reason:'Klare, kurze Sätze, wenn schnelle Hilfe nötig ist',lines:[['🙂','Ihr','J’ai besoin d’aide.','I need help.','Ich brauche Hilfe.'],['🙂','Ihr','Appelez un médecin, s’il vous plaît.','Please call a doctor.','Rufen Sie bitte einen Arzt.'],['🙂','Ihr','Où est la pharmacie la plus proche ?','Where is the nearest pharmacy?','Wo ist die nächste Apotheke?']]},
    {id:'checkout',category:'hotel',icon:'🧳',title:'Check-out und Abreise',reason:'Gepäck, Rechnung und Verabschiedung',lines:[['🙂','Ihr','Bonjour, nous souhaitons libérer la chambre.','Hello, we would like to check out.','Guten Tag, wir möchten auschecken.'],['🙂','Ihr','Pouvons-nous laisser nos bagages ici ?','Can we leave our luggage here?','Können wir unser Gepäck hier lassen?'],['🙂','Ihr','Merci pour votre accueil.','Thank you for your hospitality.','Vielen Dank für Ihre Gastfreundschaft.']]}
  ];
  const pois=situations.filter(s=>s.coords);
  let active='hotel', favoritesOnly=false, studyIndex=0, currentSituation=null, lastPosition=null;
  const favKey='parisLanguageFavorites', langKey='parisLanguageMode';
  let language=localStorage.getItem(langKey)||'fr';
  let favorites=new Set(JSON.parse(localStorage.getItem(favKey)||'[]'));
  const cats=document.getElementById('coachCategories'), list=document.getElementById('coachPhraseList'), dialogsEl=document.getElementById('coachDialogs');
  const toast=(msg)=>{const e=document.getElementById('coachToast');e.textContent=msg;e.classList.add('is-visible');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('is-visible'),1800)};
  const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  function syncLanguageButtons(){document.querySelectorAll('[data-coach-language]').forEach(b=>b.classList.toggle('is-active',b.dataset.coachLanguage===language));}
  function renderCategories(){cats.innerHTML=categories.map(c=>`<button class="coach-category ${c.id===active?'is-active':''}" type="button" data-category="${c.id}"><span>${c.icon}</span>${c.label}</button>`).join('');}
  function filtered(){return phrases.filter(p=>(favoritesOnly?favorites.has(p.id):p.category===active));}
  function audioButtons(p){if(language==='all')return `<span class="audio-pair"><button type="button" data-speak="${p.id}" data-lang="fr" title="Französisch anhören">🔊🇫🇷</button><button type="button" data-speak="${p.id}" data-lang="en" title="Englisch anhören">🔊🇬🇧</button></span>`;return `<button type="button" data-speak="${p.id}" data-lang="${language}" title="Anhören">🔊</button>`;}
  function renderPhrases(){
    const data=filtered();
    list.innerHTML=data.length?data.map(p=>`<article class="coach-phrase-card" data-id="${p.id}"><div><div class="phrase-topic">${esc(p.topic)}</div><div class="phrase-line"><span class="phrase-flag">🇩🇪</span><div class="phrase-text"><strong>${esc(p.de)}</strong></div></div><div class="phrase-line phrase-french" ${language==='en'?'hidden':''}><span class="phrase-flag">🇫🇷</span><div class="phrase-text"><strong>${esc(p.fr)}</strong><span>${esc(p.pron)}</span></div></div><div class="phrase-line" ${language==='fr'?'hidden':''}><span class="phrase-flag">🇬🇧</span><div class="phrase-text"><strong>${esc(p.en)}</strong></div></div></div><div class="phrase-actions">${audioButtons(p)}<button type="button" data-copy="${p.id}" title="Satz kopieren">📋</button><button type="button" data-favorite="${p.id}" class="${favorites.has(p.id)?'is-favorite':''}" title="Merken">${favorites.has(p.id)?'♥':'♡'}</button></div></article>`).join(''):`<div class="coach-empty"><b>Noch keine Lieblingssätze</b>Markiert Sätze mit dem Herz, damit sie hier erscheinen.</div>`;
    renderSituation();updateStudy(true);
  }
  function renderSituation(){
    if(favoritesOnly){dialogsEl.innerHTML='';return}
    const s=currentSituation||chooseSituation(); if(!s)return;
    const distance=s.distance!=null?`<span class="situation-distance">📍 ${s.distance<1000?Math.round(s.distance)+' m':(s.distance/1000).toFixed(1)+' km'} entfernt</span>`:'';
    dialogsEl.innerHTML=`<h3>💬 Situation des Moments</h3><article class="situation-card"><div class="situation-kicker"><small>${s.icon} Wahrscheinlich braucht ihr das gleich</small>${distance}</div><h4>${esc(s.title)}</h4><p class="situation-reason">${esc(s.reason)}</p>${s.lines.map(l=>`<div class="dialog-line"><span>${l[0]}</span><b>${esc(l[1])}:</b><span>${esc(language==='en'?l[3]:l[2])}</span></div>${language==='all'?`<div class="dialog-translation">🇫🇷 ${esc(l[2])}</div><div class="dialog-translation en">🇬🇧 ${esc(l[3])}</div>`:`<div class="dialog-translation">🇩🇪 ${esc(l[4])}</div>`}`).join('')}<div class="dialog-audio-row">${language!=='en'?`<button type="button" data-dialog-speak="fr">🔊 Französisch</button>`:''}${language!=='fr'?`<button type="button" data-dialog-speak="en">🔊 Englisch</button>`:''}</div></article>`;
  }
  function speakText(text,lang){if(!('speechSynthesis' in window)){toast('Sprachausgabe wird hier nicht unterstützt');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=lang==='en'?'en-GB':'fr-FR';u.rate=.82;speechSynthesis.speak(u)}
  async function copy(p){const text=language==='fr'?p.fr:language==='en'?p.en:`${p.fr}\n${p.en}`;try{await navigator.clipboard.writeText(text);toast(language==='all'?'Französisch & Englisch kopiert':'Satz kopiert')}catch(e){toast('Kopieren nicht möglich')}}
  function updateStudy(reset=false){const data=filtered();if(reset)studyIndex=0;if(!data.length){document.getElementById('studyPrompt').textContent='Noch keine Karten vorhanden.';return}studyIndex%=data.length;const p=data[studyIndex],card=document.getElementById('studyCard');card.classList.remove('is-revealed');document.getElementById('studyProgress').textContent=`Karte ${studyIndex+1} von ${data.length} · ${p.topic}`;document.getElementById('studyPrompt').textContent=p.de;document.getElementById('studyAnswer').textContent=language==='fr'?p.fr:language==='en'?p.en:`${p.fr} · ${p.en}`;document.getElementById('studyPronunciation').textContent=language==='en'?'Englische Aussprache über Audio verfügbar':p.pron;document.getElementById('studyFeedback').textContent='';document.getElementById('studyReveal').textContent='Lösung zeigen';}
  function parisNow(){return new Date(new Date().toLocaleString('en-US',{timeZone:'Europe/Paris'}));}
  function fallbackSituation(){const now=parisNow(),date=now.toISOString().slice(0,10),h=now.getHours();if(date==='2026-07-31')return h<14?'hotel-checkin':h>=17?'perruche':h<17?'metro':'hotel-checkin';if(date==='2026-08-01')return h<10?'metro':h<23?'disney':'hotel-checkin';if(date==='2026-08-02')return h<10?'checkout':h<15?'cafe':h<19?'elio':'checkout';if(h<10)return 'hotel-checkin';if(h<14)return 'metro';if(h<18)return 'cafe';if(h<22)return 'restaurant';return 'hotel-checkin';}
  function chooseSituation(){if(lastPosition){let nearest=null;for(const p of pois){const d=distance(lastPosition.latitude,lastPosition.longitude,p.coords[0],p.coords[1]);if((!nearest||d<nearest.distance)&&d<=p.radius)nearest={...p,distance:d}}if(nearest)return nearest}const id=fallbackSituation();return situations.find(s=>s.id===id)||situations.find(s=>s.category===active)||situations[0];}
  function distance(a,b,c,d){const R=6371000,toRad=x=>x*Math.PI/180,da=toRad(c-a),db=toRad(d-b),q=Math.sin(da/2)**2+Math.cos(toRad(a))*Math.cos(toRad(c))*Math.sin(db/2)**2;return 2*R*Math.asin(Math.sqrt(q));}
  function updateContext(){currentSituation=chooseSituation();const s=currentSituation;document.getElementById('coachContextIcon').textContent=s.icon;document.getElementById('coachContextTitle').textContent=s.title;document.getElementById('coachContextText').textContent=s.reason;document.getElementById('coachContextButton').onclick=()=>{active=s.category;favoritesOnly=false;document.getElementById('coachFavorites').classList.remove('is-active');renderCategories();renderPhrases();root.scrollIntoView({behavior:'smooth',block:'start'})};renderSituation();}
  function enableGPS(){const state=document.getElementById('coachLocationState');if(!navigator.geolocation){state.textContent='📍 GPS nicht verfügbar';return}state.textContent='📍 Standort wird ermittelt …';navigator.geolocation.watchPosition(pos=>{lastPosition=pos.coords;state.textContent='📍 Standort aktiv · Situation automatisch';state.classList.add('is-live');updateContext()},err=>{state.innerHTML='📍 Standort nicht aktiv · <button class="location-permission" type="button">erneut erlauben</button>';state.querySelector('button')?.addEventListener('click',enableGPS)},{enableHighAccuracy:true,maximumAge:60000,timeout:12000})}
  cats.addEventListener('click',e=>{const b=e.target.closest('[data-category]');if(!b)return;active=b.dataset.category;favoritesOnly=false;currentSituation=situations.find(s=>s.category===active)||currentSituation;document.getElementById('coachFavorites').classList.remove('is-active');document.getElementById('coachFavorites').textContent='♡ Meine Sätze';renderCategories();renderPhrases()});
  list.addEventListener('click',e=>{const id=e.target.dataset.speak||e.target.dataset.copy||e.target.dataset.favorite;if(!id)return;const p=phrases.find(x=>x.id===id);if(e.target.dataset.speak)speakText(e.target.dataset.lang==='en'?p.en:p.fr,e.target.dataset.lang);if(e.target.dataset.copy)copy(p);if(e.target.dataset.favorite){favorites.has(id)?favorites.delete(id):favorites.add(id);localStorage.setItem(favKey,JSON.stringify([...favorites]));renderPhrases();toast(favorites.has(id)?'Zu „Meine Sätze“ hinzugefügt':'Aus Favoriten entfernt')}});
  dialogsEl.addEventListener('click',e=>{const lang=e.target.dataset.dialogSpeak;if(!lang||!currentSituation)return;const text=currentSituation.lines.map(l=>lang==='en'?l[3]:l[2]).join('. ');speakText(text,lang)});
  document.querySelectorAll('[data-coach-language]').forEach(b=>b.addEventListener('click',()=>{language=b.dataset.coachLanguage;localStorage.setItem(langKey,language);syncLanguageButtons();renderPhrases()}));
  document.querySelectorAll('[data-coach-mode]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-coach-mode]').forEach(x=>x.classList.toggle('is-active',x===b));root.dataset.mode=b.dataset.coachMode;updateStudy(true)}));
  document.getElementById('coachFavorites').addEventListener('click',function(){favoritesOnly=!favoritesOnly;this.classList.toggle('is-active',favoritesOnly);this.textContent=favoritesOnly?'♥ Meine Sätze':'♡ Meine Sätze';renderCategories();renderPhrases()});
  document.getElementById('studyReveal').addEventListener('click',()=>{const card=document.getElementById('studyCard');card.classList.toggle('is-revealed');document.getElementById('studyReveal').textContent=card.classList.contains('is-revealed')?'Lösung verbergen':'Lösung zeigen'});
  document.getElementById('studyNext').addEventListener('click',()=>{studyIndex++;updateStudy()});
  syncLanguageButtons();renderCategories();updateContext();renderPhrases();enableGPS();setInterval(updateContext,60000);
})();
