(() => {
  'use strict';
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  function css(){if(document.getElementById('parisAuthCss'))return;const s=document.createElement('style');s.id='parisAuthCss';s.textContent=`
  .pa-stack{display:grid;gap:14px}.pa-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.pa-field{display:grid;gap:7px}.pa-field label{font-size:13px;font-weight:850;color:#536b7c}.pa-field input{width:100%;box-sizing:border-box;border:1px solid #dfe6e9;border-radius:14px;padding:13px 14px;background:#f8fafb;color:#314b60;font:600 16px system-ui;outline:none}.pa-field input:focus{border-color:#db7996;box-shadow:0 0 0 4px rgba(219,121,150,.12);background:#fff}.pa-wide{grid-column:1/-1}.pa-actions{display:flex;gap:9px;flex-wrap:wrap}.pa-provider{width:100%;border:1px solid #dfe5e8;border-radius:15px;padding:13px;background:#fff;color:#354f62;font-weight:850;cursor:pointer}.pa-provider.apple{background:#111;color:#fff;border-color:#111}.pa-provider.google{background:#fff}.pa-status{padding:13px 14px;border-radius:14px;background:#eef8f5;color:#34745c;line-height:1.45;font-size:14px}.pa-status.warn{background:#fff5e8;color:#8b632b}.pa-status.error{background:#fff0f1;color:#a94455}.pa-divider{display:flex;align-items:center;gap:10px;color:#98a5ad;font-size:12px}.pa-divider:before,.pa-divider:after{content:"";height:1px;background:#e5eaec;flex:1}.pa-link{border:0;background:none;color:#b54e71;font-weight:800;padding:4px;cursor:pointer}.pa-account-hero{display:flex;align-items:center;gap:14px}.pa-avatar{width:58px;height:58px;border-radius:18px;background:linear-gradient(145deg,#e86e94,#bd5f81);color:#fff;display:grid;place-items:center;font:900 24px Georgia}.pa-muted{color:#7b8b96;font-size:14px;line-height:1.55}.pa-security{display:grid;gap:10px}.pa-chip{display:inline-flex;padding:6px 10px;border-radius:999px;background:#eef8f5;color:#34745c;font-size:12px;font-weight:900}.pa-chip.anon{background:#fff5e8;color:#966323}@media(max-width:520px){.pa-grid{grid-template-columns:1fr}.pa-wide{grid-column:auto}.pa-actions{display:grid}.pa-actions>*{width:100%}}
  `;document.head.appendChild(s)}
  function auth(){return window.ParisAuth}
  function message(box,text,type=''){box.innerHTML=`<div class="pa-status ${type}">${esc(text)}</div>`}
  function validate(email,password,repeat){if(!/^\S+@\S+\.\S+$/.test(email))throw new Error('Bitte gib eine gültige E-Mail-Adresse ein.');if(password.length<8)throw new Error('Das Passwort muss mindestens 8 Zeichen haben.');if(repeat!==undefined&&password!==repeat)throw new Error('Die Passwörter stimmen nicht überein.')}
  function baseForm(mode,state){
    const anonymous=state.anonymous;
    const title=mode==='secure'?'Anonymes Konto sichern':mode==='register'?'Konto erstellen':'Anmelden';
    const profileFields=mode!=='login'?`<div class="pa-field"><label>Vorname</label><input name="firstName" autocomplete="given-name"></div><div class="pa-field"><label>Nachname</label><input name="lastName" autocomplete="family-name"></div><div class="pa-field pa-wide"><label>Anzeigename</label><input name="displayName" autocomplete="nickname" value="${esc(window.ParisCloud?.memberName||'')}"></div>`:'';
    const repeat=mode!=='login'?`<div class="pa-field pa-wide"><label>Passwort wiederholen</label><input name="repeat" type="password" autocomplete="new-password"></div>`:'';
    return `<div class="pa-stack"><div><h3 style="margin:0 0 6px;color:#355066;font:900 25px Georgia">${title}</h3><div class="pa-muted">${mode==='secure'?'Deine bestehende Reise bleibt mit genau derselben Benutzer-ID verbunden. Nach der E-Mail-Bestätigung kannst du dich auf weiteren Geräten anmelden.':mode==='register'?'Erstelle ein dauerhaftes Paris-Konto.':'Melde dich mit deinem bestehenden Paris-Konto an.'}</div></div><form class="pa-grid" data-auth-form>${profileFields}<div class="pa-field pa-wide"><label>E-Mail-Adresse</label><input name="email" type="email" inputmode="email" autocomplete="email" required></div><div class="pa-field pa-wide"><label>Passwort</label><input name="password" type="password" autocomplete="${mode==='login'?'current-password':'new-password'}" required></div>${repeat}<div class="pa-wide pa-actions"><button class="pc-btn primary" type="submit">${title}</button>${mode==='login'?'<button class="pa-link" type="button" data-forgot>Passwort vergessen</button>':''}</div></form><div data-auth-message></div>${mode!=='secure'?`<div class="pa-divider">oder</div><button class="pa-provider apple" data-provider="apple"> Mit Apple fortfahren</button><button class="pa-provider google" data-provider="google">G Mit Google fortfahren</button><button class="pa-link" data-switch type="button">${mode==='login'?'Noch kein Konto? Jetzt registrieren':'Schon registriert? Anmelden'}</button>`:''}${anonymous&&mode!=='secure'?'<div class="pa-status warn">Auf diesem Gerät ist noch ein anonymes Reisekonto aktiv. Nutze besser „Konto sichern“, damit bestehende Daten nicht getrennt werden.</div>':''}</div>`;
  }
  function bindForm(container,mode){
    const form=container.querySelector('[data-auth-form]'),box=container.querySelector('[data-auth-message]');
    form.onsubmit=async e=>{e.preventDefault();const fd=new FormData(form),email=String(fd.get('email')||'').trim(),password=String(fd.get('password')||''),repeat=mode==='login'?undefined:String(fd.get('repeat')||'');try{validate(email,password,repeat);message(box,'Wird verarbeitet …');const payload={email,password,firstName:String(fd.get('firstName')||''),lastName:String(fd.get('lastName')||''),displayName:String(fd.get('displayName')||'')};if(mode==='secure')await auth().secureAnonymousAccount(payload);else if(mode==='register')await auth().signUp(payload);else await auth().signIn(email,password);message(box,mode==='login'?'Anmeldung erfolgreich. Die App wird aktualisiert.':'Fast geschafft: Bitte bestätige jetzt die E-Mail, die Supabase an dich gesendet hat.');if(mode==='login')setTimeout(()=>location.reload(),700)}catch(err){message(box,err.message||'Die Aktion konnte nicht abgeschlossen werden.','error')}};
    container.querySelector('[data-forgot]')?.addEventListener('click',async()=>{const email=form.elements.email.value.trim();if(!email){message(box,'Trage zuerst deine E-Mail-Adresse ein.','warn');return}try{await auth().resetPassword(email);message(box,'Die E-Mail zum Zurücksetzen des Passworts wurde versendet.')}catch(err){message(box,err.message,'error')}});
    container.querySelector('[data-switch]')?.addEventListener('click',()=>renderAuthForm(container,mode==='login'?'register':'login'));
    container.querySelectorAll('[data-provider]').forEach(b=>b.onclick=async()=>{try{message(box,`${b.dataset.provider==='apple'?'Apple':'Google'} wird geöffnet …`);await auth().signInWithProvider(b.dataset.provider)}catch(err){message(box,err.message||'Dieser Anbieter ist in Supabase noch nicht fertig eingerichtet.','error')}})
  }
  function renderAuthForm(container,mode){container.innerHTML=baseForm(mode,auth().getState());bindForm(container,mode)}
  function render(container){
    css(); const st=auth()?.getState?.()||{loading:true};
    if(st.loading){container.innerHTML='<div class="pc-card">Kontostatus wird geladen …</div>';return}
    if(st.anonymous){container.innerHTML=`<div class="pc-head"><div><h2>Konto</h2><p>Sichere deine bestehende Reise dauerhaft.</p></div></div><div class="pc-card"><div class="pa-account-hero"><div class="pa-avatar">${esc((window.ParisCloud?.memberName||'P').charAt(0).toUpperCase())}</div><div><b style="font-size:20px;color:#355066">${esc(window.ParisCloud?.memberName||'Anonymes Reisekonto')}</b><div class="pa-muted">Nur auf diesem Gerät wiederherstellbar</div><span class="pa-chip anon">Anonym</span></div></div><div class="pc-note" style="margin-top:18px">Sichere dieses Konto, bevor du dich abmeldest oder Browserdaten löschst. Reise, Fotos, Momente und Teilnehmerzuordnung bleiben dabei erhalten.</div><div style="margin-top:18px" data-account-form></div></div>`;renderAuthForm(container.querySelector('[data-account-form]'),'secure');return}
    const name=st.user?.user_metadata?.display_name||st.user?.user_metadata?.full_name||window.ParisCloud?.memberName||st.email;
    container.innerHTML=`<div class="pc-head"><div><h2>Konto</h2><p>Anmeldung, Sicherheit und verbundene Methoden.</p></div></div><div class="pc-card pa-stack"><div class="pa-account-hero"><div class="pa-avatar">${esc(String(name||'P').charAt(0).toUpperCase())}</div><div><b style="font-size:20px;color:#355066">${esc(name)}</b><div class="pa-muted">${esc(st.email)}</div><span class="pa-chip">Dauerhaft gesichert</span></div></div><div class="pc-row"><div><b>Anmeldemethode</b><div class="pc-meta">${esc(st.provider)}</div></div><span>${st.identities.length} verbunden</span></div><div class="pc-row"><div><b>Weitere Anmeldung verbinden</b><div class="pc-meta">Dasselbe Konto auch über Apple oder Google verwenden.</div></div><div class="pa-actions"><button class="pc-btn" data-link="apple"> Apple</button><button class="pc-btn" data-link="google">G Google</button></div></div><div class="pc-row"><div><b>Passwort ändern</b><div class="pc-meta">Mindestens 8 Zeichen.</div></div><button class="pc-btn" data-password>Ändern</button></div><div class="pc-row"><div><b>Auf diesem Gerät abmelden</b><div class="pc-meta">Cloud-Daten bleiben erhalten.</div></div><button class="pc-btn danger" data-signout>Abmelden</button></div><div data-account-message></div></div>`;
    const box=container.querySelector('[data-account-message]');container.querySelectorAll('[data-link]').forEach(b=>b.onclick=async()=>{try{await auth().linkProvider(b.dataset.link)}catch(err){message(box,err.message,'error')}});container.querySelector('[data-password]').onclick=async()=>{const p=prompt('Neues Passwort (mindestens 8 Zeichen):');if(!p)return;try{if(p.length<8)throw new Error('Das Passwort muss mindestens 8 Zeichen haben.');await auth().updatePassword(p);message(box,'Passwort wurde aktualisiert.')}catch(err){message(box,err.message,'error')}};container.querySelector('[data-signout]').onclick=()=>{if(confirm('Auf diesem Gerät wirklich abmelden?'))auth().signOut()}
  }
  window.ParisAuthUI={render,renderAuthForm};
})();
