(() => {
  'use strict';
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  function css(){if(document.getElementById('parisAuthCss'))return;const s=document.createElement('style');s.id='parisAuthCss';s.textContent=`
  .pa-stack{display:grid;gap:14px}.pa-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.pa-field{display:grid;gap:7px}.pa-field label{font-size:13px;font-weight:850;color:#536b7c}.pa-field input{width:100%;box-sizing:border-box;border:1px solid #dfe6e9;border-radius:14px;padding:13px 14px;background:#f8fafb;color:#314b60;font:600 16px system-ui;outline:none}.pa-field input:focus{border-color:#db7996;box-shadow:0 0 0 4px rgba(219,121,150,.12);background:#fff}.pa-wide{grid-column:1/-1}.pa-actions{display:flex;gap:9px;flex-wrap:wrap}.pa-provider{width:100%;border:1px solid #dfe5e8;border-radius:15px;padding:13px;background:#fff;color:#354f62;font-weight:850;cursor:pointer}.pa-provider.apple{background:#111;color:#fff;border-color:#111}.pa-status{padding:13px 14px;border-radius:14px;background:#eef8f5;color:#34745c;line-height:1.45;font-size:14px}.pa-status.warn{background:#fff5e8;color:#8b632b}.pa-status.error{background:#fff0f1;color:#a94455}.pa-divider{display:flex;align-items:center;gap:10px;color:#98a5ad;font-size:12px}.pa-divider:before,.pa-divider:after{content:"";height:1px;background:#e5eaec;flex:1}.pa-link{border:0;background:none;color:#b54e71;font-weight:800;padding:4px;cursor:pointer}.pa-account-hero{display:flex;align-items:center;gap:14px}.pa-avatar{width:58px;height:58px;border-radius:18px;background:linear-gradient(145deg,#e86e94,#bd5f81);color:#fff;display:grid;place-items:center;font:900 24px Georgia}.pa-muted{color:#7b8b96;font-size:14px;line-height:1.55}.pa-chip{display:inline-flex;padding:6px 10px;border-radius:999px;background:#eef8f5;color:#34745c;font-size:12px;font-weight:900}.pa-chip.anon{background:#fff5e8;color:#966323}.pa-progress{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin:4px 0 8px}.pa-progress span{height:6px;border-radius:999px;background:#e8edef}.pa-progress span.on{background:linear-gradient(90deg,#e86e94,#bd5f81)}.pa-stepmark{font-size:12px;font-weight:900;letter-spacing:.12em;text-transform:uppercase;color:#b15c79}.pa-mail-hero{text-align:center;padding:8px 4px}.pa-mail-icon{width:74px;height:74px;border-radius:24px;margin:0 auto 14px;display:grid;place-items:center;background:#fff0f5;font-size:34px}.pa-checklist{display:grid;gap:9px;margin:4px 0}.pa-checkitem{display:flex;gap:10px;align-items:flex-start;color:#627684;font-size:14px;line-height:1.45}.pa-checkitem b{color:#355066}.pa-security{display:grid;gap:10px}.pa-login-note{padding:14px;border:1px solid #f1d8e2;border-radius:16px;background:#fff8fb;color:#6d5862;font-size:14px;line-height:1.5}.pa-guest{width:100%;margin-top:4px}@media(max-width:520px){.pa-grid{grid-template-columns:1fr}.pa-wide{grid-column:auto}.pa-actions{display:grid}.pa-actions>*{width:100%}}
  `;document.head.appendChild(s)}
  function auth(){return window.ParisAuth}
  function message(box,text,type=''){box.innerHTML=`<div class="pa-status ${type}">${esc(text)}</div>`}
  function validEmail(email){return /^\S+@\S+\.\S+$/.test(email)}
  function progress(step){return `<div class="pa-progress" aria-label="Schritt ${step} von 3"><span class="on"></span><span class="${step>=2?'on':''}"></span><span class="${step>=3?'on':''}"></span></div>`}

  function standardForm(mode,state){
    const anonymous=state.anonymous;
    const title=mode==='register'?'Konto erstellen':'Anmelden';
    const profileFields=mode!=='login'?`<div class="pa-field"><label>Vorname</label><input name="firstName" autocomplete="given-name"></div><div class="pa-field"><label>Nachname</label><input name="lastName" autocomplete="family-name"></div><div class="pa-field pa-wide"><label>Anzeigename</label><input name="displayName" autocomplete="nickname" value="${esc(window.ParisCloud?.memberName||'')}"></div>`:'';
    const repeat=mode!=='login'?`<div class="pa-field pa-wide"><label>Passwort wiederholen</label><input name="repeat" type="password" autocomplete="new-password"></div>`:'';
    return `<div class="pa-stack"><div><h3 style="margin:0 0 6px;color:#355066;font:900 25px Georgia">${title}</h3><div class="pa-muted">${mode==='register'?'Erstelle dein dauerhaftes Reisekonto.':'Melde dich mit deinem bestehenden Reisekonto an.'}</div></div><form class="pa-grid" data-auth-form>${profileFields}<div class="pa-field pa-wide"><label>E-Mail-Adresse</label><input name="email" type="email" inputmode="email" autocomplete="email" required></div><div class="pa-field pa-wide"><label>Passwort</label><input name="password" type="password" autocomplete="${mode==='login'?'current-password':'new-password'}" required></div>${repeat}<div class="pa-wide pa-actions"><button class="pc-btn primary" type="submit">${title}</button>${mode==='login'?'<button class="pa-link" type="button" data-forgot>Passwort vergessen</button>':''}</div></form><div data-auth-message></div><div class="pa-divider">oder</div><button class="pa-provider apple" data-provider="apple"><span class="provider-icon" aria-hidden="true"><svg viewBox="0 0 24 24" fill="currentColor"><path d="M17.05 12.54c-.03-3 2.45-4.45 2.56-4.52-1.4-2.05-3.58-2.33-4.35-2.36-1.83-.19-3.61 1.1-4.54 1.1-.95 0-2.38-1.08-3.93-1.05-1.99.03-3.85 1.18-4.87 2.95-2.11 3.65-.54 9.02 1.48 11.97 1.01 1.44 2.18 3.05 3.73 2.99 1.51-.06 2.07-.96 3.89-.96 1.8 0 2.33.96 3.9.92 1.63-.03 2.65-1.44 3.62-2.89 1.17-1.65 1.64-3.28 1.66-3.36-.04-.01-3.13-1.2-3.16-4.79ZM14.07 3.72A4.2 4.2 0 0 0 15.03.7a4.28 4.28 0 0 0-2.77 1.44 4.02 4.02 0 0 0-.99 2.91 3.54 3.54 0 0 0 2.8-1.33Z"/></svg></span><span>Mit Apple fortfahren</span></button><button class="pa-provider google" data-provider="google"><span class="provider-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path fill="#4285F4" d="M21.6 12.23c0-.71-.06-1.4-.18-2.06H12v3.9h5.38a4.6 4.6 0 0 1-2 3.02v2.53h3.24c1.9-1.75 2.98-4.33 2.98-7.39Z"/><path fill="#34A853" d="M12 22c2.7 0 4.97-.9 6.62-2.38l-3.24-2.53c-.9.6-2.05.96-3.38.96-2.61 0-4.82-1.76-5.61-4.13H3.04v2.61A10 10 0 0 0 12 22Z"/><path fill="#FBBC05" d="M6.39 13.92A6.02 6.02 0 0 1 6.07 12c0-.67.12-1.31.32-1.92V7.47H3.04A10 10 0 0 0 2 12c0 1.61.38 3.13 1.04 4.53l3.35-2.61Z"/><path fill="#EA4335" d="M12 5.95c1.47 0 2.78.5 3.82 1.49l2.87-2.87A9.62 9.62 0 0 0 12 2a10 10 0 0 0-8.96 5.47l3.35 2.61C7.18 7.71 9.39 5.95 12 5.95Z"/></svg></span><span>Mit Google fortfahren</span></button><button class="pa-link" data-switch type="button">${mode==='login'?'Noch kein Konto? Jetzt registrieren':'Schon registriert? Anmelden'}</button>${anonymous?'<div class="pa-login-note"><b>Anonymes Reisekonto aktiv.</b><br>Mit der Anmeldung wechselst du jetzt direkt zu deinem bereits angelegten E-Mail-Konto.</div>':''}</div>`;
  }
  function bindStandard(container,mode){
    const form=container.querySelector('[data-auth-form]'),box=container.querySelector('[data-auth-message]');
    form.onsubmit=async e=>{e.preventDefault();const fd=new FormData(form),email=String(fd.get('email')||'').trim(),password=String(fd.get('password')||''),repeat=mode==='login'?undefined:String(fd.get('repeat')||'');try{if(!validEmail(email))throw new Error('Bitte gib eine gültige E-Mail-Adresse ein.');if(mode!=='login'&&password.length<8)throw new Error('Das Passwort muss mindestens 8 Zeichen haben.');if(repeat!==undefined&&password!==repeat)throw new Error('Die Passwörter stimmen nicht überein.');message(box,'Wird verarbeitet …');const payload={email,password,firstName:String(fd.get('firstName')||''),lastName:String(fd.get('lastName')||''),displayName:String(fd.get('displayName')||'')};if(mode==='register')await auth().signUp(payload);else await auth().signIn(email,password);message(box,mode==='login'?'Anmeldung erfolgreich. Die App wird aktualisiert.':'Fast geschafft: Bitte bestätige jetzt die E-Mail, die Supabase an dich gesendet hat.');if(mode==='login'){await auth().refreshCurrentUser?.();document.dispatchEvent(new CustomEvent('reisezeit:login-success',{detail:auth().getState()}))}}catch(err){message(box,err.message||'Die Aktion konnte nicht abgeschlossen werden.','error')}};
    container.querySelector('[data-forgot]')?.addEventListener('click',async()=>{const email=form.elements.email.value.trim();if(!email){message(box,'Trage zuerst deine E-Mail-Adresse ein.','warn');return}try{await auth().resetPassword(email);message(box,'Die E-Mail zum Zurücksetzen des Passworts wurde versendet.')}catch(err){message(box,err.message,'error')}});
    container.querySelector('[data-switch]')?.addEventListener('click',()=>renderAuthForm(container,mode==='login'?'register':'login'));
    container.querySelectorAll('[data-provider]').forEach(b=>b.onclick=async()=>{try{message(box,`${b.dataset.provider==='apple'?'Apple':'Google'} wird geöffnet …`);await auth().signInWithProvider(b.dataset.provider)}catch(err){message(box,err.message||'Dieser Anbieter ist in Supabase noch nicht fertig eingerichtet.','error')}})
  }
  function renderAuthForm(container,mode){container.innerHTML=standardForm(mode,auth().getState());bindStandard(container,mode)}

  function wizardStep1(container,st){
    const p=st.pendingUpgrade||{};
    container.innerHTML=`<div class="pa-stack">${progress(1)}<div><div class="pa-stepmark">Schritt 1 von 3</div><h3 style="margin:6px 0;color:#355066;font:900 25px Georgia">E-Mail verknüpfen</h3><div class="pa-muted">Zuerst wird nur deine E-Mail-Adresse mit dem bestehenden anonymen Konto verbunden. Das Passwort folgt erst nach der Bestätigung.</div></div><form class="pa-grid" data-upgrade-email><div class="pa-field"><label>Vorname</label><input name="firstName" autocomplete="given-name" value="${esc(p.firstName||'')}"></div><div class="pa-field"><label>Nachname</label><input name="lastName" autocomplete="family-name" value="${esc(p.lastName||'')}"></div><div class="pa-field pa-wide"><label>Anzeigename</label><input name="displayName" autocomplete="nickname" value="${esc(p.displayName||window.ParisCloud?.memberName||'')}"></div><div class="pa-field pa-wide"><label>E-Mail-Adresse</label><input name="email" type="email" inputmode="email" autocomplete="email" value="${esc(p.email||'')}" required></div><div class="pa-wide pa-actions"><button class="pc-btn primary" type="submit">Bestätigungsmail senden</button></div></form><div data-upgrade-message></div></div>`;
    const form=container.querySelector('[data-upgrade-email]'),box=container.querySelector('[data-upgrade-message]');
    form.onsubmit=async e=>{e.preventDefault();const fd=new FormData(form),email=String(fd.get('email')||'').trim();try{if(!validEmail(email))throw new Error('Bitte gib eine gültige E-Mail-Adresse ein.');message(box,'Bestätigungsmail wird vorbereitet …');await auth().requestAnonymousEmail({email,firstName:String(fd.get('firstName')||''),lastName:String(fd.get('lastName')||''),displayName:String(fd.get('displayName')||'')});wizardStep2(container,auth().getState())}catch(err){message(box,err.message||'Die Bestätigungsmail konnte nicht gesendet werden.','error')}};
  }
  function wizardStep2(container,st){
    const p=st.pendingUpgrade||{};
    container.innerHTML=`<div class="pa-stack">${progress(2)}<div class="pa-mail-hero"><div class="pa-mail-icon">✉️</div><div class="pa-stepmark">Schritt 2 von 3</div><h3 style="margin:7px 0;color:#355066;font:900 25px Georgia">E-Mail bestätigen</h3><div class="pa-muted">Wir haben eine Bestätigung an <b>${esc(p.email||st.email)}</b> gesendet.</div></div><div class="pa-checklist"><div class="pa-checkitem"><span>1.</span><div>Öffne die E-Mail von Supabase und tippe auf den Bestätigungslink.</div></div><div class="pa-checkitem"><span>2.</span><div>Du wirst zurück zur Paris-App geleitet.</div></div><div class="pa-checkitem"><span>3.</span><div>Tippe danach hier auf <b>„Bestätigung prüfen“</b>.</div></div></div><div class="pa-actions"><button class="pc-btn primary" data-check>Bestätigung prüfen</button><button class="pc-btn" data-resend>Mail erneut senden</button><button class="pa-link" data-change>Andere E-Mail verwenden</button></div><div data-upgrade-message></div></div>`;
    const box=container.querySelector('[data-upgrade-message]');
    container.querySelector('[data-check]').onclick=async()=>{try{message(box,'Bestätigung wird geprüft …');const result=await auth().checkUpgradeConfirmation();if(!result.confirmed){message(box,'Noch nicht bestätigt. Öffne den Link aus der E-Mail und versuche es danach erneut.','warn');return}wizardStep3(container,auth().getState())}catch(err){message(box,err.message||'Die Bestätigung konnte nicht geprüft werden.','error')}};
    container.querySelector('[data-resend]').onclick=async()=>{try{message(box,'Neue Bestätigungsmail wird gesendet …');await auth().requestAnonymousEmail(p);message(box,'Eine neue Bestätigungsmail wurde gesendet.')}catch(err){message(box,err.message||'Die E-Mail konnte nicht erneut gesendet werden.','error')}};
    container.querySelector('[data-change]').onclick=()=>{auth().cancelPendingUpgrade();wizardStep1(container,auth().getState())};
  }
  function wizardStep3(container,st){
    const p=st.pendingUpgrade||{};
    container.innerHTML=`<div class="pa-stack">${progress(3)}<div><div class="pa-stepmark">Schritt 3 von 3</div><h3 style="margin:6px 0;color:#355066;font:900 25px Georgia">Passwort festlegen</h3><div class="pa-muted">Deine E-Mail <b>${esc(p.email||st.email)}</b> ist bestätigt. Lege jetzt das Passwort für Anmeldungen auf weiteren Geräten fest.</div></div><form class="pa-grid" data-upgrade-password><div class="pa-field pa-wide"><label>Passwort</label><input name="password" type="password" autocomplete="new-password" required></div><div class="pa-field pa-wide"><label>Passwort wiederholen</label><input name="repeat" type="password" autocomplete="new-password" required></div><div class="pa-wide pa-actions"><button class="pc-btn primary" type="submit">Konto abschließen</button></div></form><div data-upgrade-message></div></div>`;
    const form=container.querySelector('[data-upgrade-password]'),box=container.querySelector('[data-upgrade-message]');
    form.onsubmit=async e=>{e.preventDefault();const fd=new FormData(form),password=String(fd.get('password')||''),repeat=String(fd.get('repeat')||'');try{if(mode!=='login'&&password.length<8)throw new Error('Das Passwort muss mindestens 8 Zeichen haben.');if(password!==repeat)throw new Error('Die Passwörter stimmen nicht überein.');message(box,'Konto wird abgeschlossen …');await auth().completeAnonymousUpgrade(password);message(box,'Dein Konto ist jetzt dauerhaft gesichert.');setTimeout(()=>render(container),700)}catch(err){message(box,err.message||'Das Konto konnte nicht abgeschlossen werden.','error')}};
  }
  function renderWizard(container,st){
    const p=st.pendingUpgrade;
    if(!p){wizardStep1(container,st);return}
    if(p.stage==='email-confirmed' || (st.emailConfirmed && !st.anonymous)){wizardStep3(container,st);return}
    wizardStep2(container,st);
  }
  function render(container){
    css(); const st=auth()?.getState?.()||{loading:true};
    if(st.loading){container.innerHTML='<div class="pc-card">Kontostatus wird geladen …</div>';return}
    if(!st.user){
      container.innerHTML=`<div class="pc-head"><div><h2>Konto</h2><p>Melde dich an, um deine Reisen auf diesem Gerät zu öffnen.</p></div></div><div class="pc-card pa-stack"><div data-signed-out-auth></div><div class="pa-divider">oder</div><button class="pc-btn pa-guest" type="button" data-continue-anonymous>Ohne Konto fortfahren</button><div class="pa-muted">Dabei wird erst nach deiner ausdrücklichen Auswahl ein anonymes Konto angelegt.</div><div data-guest-message></div></div>`;
      renderAuthForm(container.querySelector('[data-signed-out-auth]'),'login');
      const guestBox=container.querySelector('[data-guest-message]');
      container.querySelector('[data-continue-anonymous]').onclick=async()=>{try{message(guestBox,'Anonymes Reisekonto wird vorbereitet …');await auth().continueAnonymously();message(guestBox,'Du nutzt die App jetzt ohne dauerhaftes Konto.');setTimeout(()=>location.reload(),500)}catch(err){message(guestBox,err.message||'Anonymes Fortfahren war nicht möglich.','error')}};
      return
    }
    if(st.anonymous){
      container.innerHTML=`<div class="pc-head"><div><h2>Konto</h2><p>Melde dich jetzt mit deinem bestehenden E-Mail-Konto an.</p></div></div><div class="pc-card pa-stack"><div class="pa-account-hero"><div class="pa-avatar">${esc((window.ParisCloud?.memberName||'P').charAt(0).toUpperCase())}</div><div><b style="font-size:20px;color:#355066">${esc(window.ParisCloud?.memberName||'Anonymes Reisekonto')}</b><div class="pa-muted">Aktuell ist noch die anonyme Gerätesitzung aktiv.</div><span class="pa-chip anon">Anonym</span></div></div><div class="pa-login-note"><b>Dein E-Mail-Konto existiert bereits.</b><br>Gib unten deine E-Mail-Adresse und dein Passwort ein. Die App ersetzt danach die anonyme Sitzung durch dein dauerhaftes Konto.</div><div data-anonymous-login></div></div>`;
      renderAuthForm(container.querySelector('[data-anonymous-login]'),'login');
      return
    }
    const name=st.user?.user_metadata?.display_name||st.user?.user_metadata?.full_name||window.ParisCloud?.memberName||st.email;
    container.innerHTML=`<div class="pc-head"><div><h2>Konto</h2><p>Anmeldung, Sicherheit und verbundene Methoden.</p></div></div><div class="pc-card pa-stack"><div class="pa-account-hero"><div class="pa-avatar">${esc(String(name||'P').charAt(0).toUpperCase())}</div><div><b style="font-size:20px;color:#355066">${esc(name)}</b><div class="pa-muted">${esc(st.email)}</div><span class="pa-chip">Dauerhaft gesichert</span></div></div><div class="pc-row"><div><b>Anmeldemethode</b><div class="pc-meta">${esc(st.provider)}</div></div><span>${st.identities.length} verbunden</span></div><div class="pc-row"><div><b>Weitere Anmeldung verbinden</b><div class="pc-meta">Dasselbe Konto auch über Apple oder Google verwenden.</div></div><div class="pa-actions"><button class="pc-btn" data-link="apple"> Apple</button><button class="pc-btn" data-link="google">G Google</button></div></div><div class="pc-row"><div><b>Passwort ändern</b><div class="pc-meta">Mindestens 8 Zeichen.</div></div><button class="pc-btn" data-password>Ändern</button></div><div class="pc-row"><div><b>Auf diesem Gerät abmelden</b><div class="pc-meta">Cloud-Daten bleiben erhalten.</div></div><button class="pc-btn danger" data-signout>Abmelden</button></div><div data-account-message></div></div>`;
    const box=container.querySelector('[data-account-message]');container.querySelectorAll('[data-link]').forEach(b=>b.onclick=async()=>{try{await auth().linkProvider(b.dataset.link)}catch(err){message(box,err.message,'error')}});container.querySelector('[data-password]').onclick=async()=>{const p=prompt('Neues Passwort (mindestens 8 Zeichen):');if(!p)return;try{if(p.length<8)throw new Error('Das Passwort muss mindestens 8 Zeichen haben.');await auth().updatePassword(p);message(box,'Passwort wurde aktualisiert.')}catch(err){message(box,err.message,'error')}};container.querySelector('[data-signout]').onclick=async()=>{if(!confirm('Auf diesem Gerät wirklich abmelden?'))return;try{message(box,'Du wirst abgemeldet …');await auth().signOut()}catch(err){message(box,err.message||'Abmelden fehlgeschlagen.','error')}}
  }
  let lastMountedContainer=null;
  const originalRender=render;
  function trackedRender(container){lastMountedContainer=container;return originalRender(container)}
  document.addEventListener('paris:auth-changed',()=>{
    if(lastMountedContainer?.isConnected) originalRender(lastMountedContainer);
  });
  window.ParisAuthUI={render:trackedRender,renderAuthForm};
})();
